// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: client_ac.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ACService_RegisterAC_FullMethodName     = "/proto.ACService/RegisterAC"
	ACService_SelectSNs_FullMethodName      = "/proto.ACService/SelectSNs"
	ACService_PutFileCommit_FullMethodName  = "/proto.ACService/PutFileCommit"
	ACService_GetFileSNs_FullMethodName     = "/proto.ACService/GetFileSNs"
	ACService_GetDSErrReport_FullMethodName = "/proto.ACService/GetDSErrReport"
	ACService_GetDSSn_FullMethodName        = "/proto.ACService/GetDSSn"
	ACService_UpdateDSCommit_FullMethodName = "/proto.ACService/UpdateDSCommit"
)

// ACServiceClient is the client API for ACService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ACServiceClient interface {
	RegisterAC(ctx context.Context, in *RegistACRequest, opts ...grpc.CallOption) (*RegistACResponse, error)
	SelectSNs(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageResponse, error)
	PutFileCommit(ctx context.Context, in *PFCRequest, opts ...grpc.CallOption) (*PFCResponse, error)
	GetFileSNs(ctx context.Context, in *GFACRequest, opts ...grpc.CallOption) (*GFACResponse, error)
	GetDSErrReport(ctx context.Context, in *GDSERequest, opts ...grpc.CallOption) (*GDSEResponse, error)
	GetDSSn(ctx context.Context, in *GDSSNRequest, opts ...grpc.CallOption) (*GDSSNResponse, error)
	UpdateDSCommit(ctx context.Context, in *UDSCRequest, opts ...grpc.CallOption) (*UDSCResponse, error)
}

type aCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewACServiceClient(cc grpc.ClientConnInterface) ACServiceClient {
	return &aCServiceClient{cc}
}

func (c *aCServiceClient) RegisterAC(ctx context.Context, in *RegistACRequest, opts ...grpc.CallOption) (*RegistACResponse, error) {
	out := new(RegistACResponse)
	err := c.cc.Invoke(ctx, ACService_RegisterAC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCServiceClient) SelectSNs(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageResponse, error) {
	out := new(StorageResponse)
	err := c.cc.Invoke(ctx, ACService_SelectSNs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCServiceClient) PutFileCommit(ctx context.Context, in *PFCRequest, opts ...grpc.CallOption) (*PFCResponse, error) {
	out := new(PFCResponse)
	err := c.cc.Invoke(ctx, ACService_PutFileCommit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCServiceClient) GetFileSNs(ctx context.Context, in *GFACRequest, opts ...grpc.CallOption) (*GFACResponse, error) {
	out := new(GFACResponse)
	err := c.cc.Invoke(ctx, ACService_GetFileSNs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCServiceClient) GetDSErrReport(ctx context.Context, in *GDSERequest, opts ...grpc.CallOption) (*GDSEResponse, error) {
	out := new(GDSEResponse)
	err := c.cc.Invoke(ctx, ACService_GetDSErrReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCServiceClient) GetDSSn(ctx context.Context, in *GDSSNRequest, opts ...grpc.CallOption) (*GDSSNResponse, error) {
	out := new(GDSSNResponse)
	err := c.cc.Invoke(ctx, ACService_GetDSSn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCServiceClient) UpdateDSCommit(ctx context.Context, in *UDSCRequest, opts ...grpc.CallOption) (*UDSCResponse, error) {
	out := new(UDSCResponse)
	err := c.cc.Invoke(ctx, ACService_UpdateDSCommit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ACServiceServer is the server API for ACService service.
// All implementations must embed UnimplementedACServiceServer
// for forward compatibility
type ACServiceServer interface {
	RegisterAC(context.Context, *RegistACRequest) (*RegistACResponse, error)
	SelectSNs(context.Context, *StorageRequest) (*StorageResponse, error)
	PutFileCommit(context.Context, *PFCRequest) (*PFCResponse, error)
	GetFileSNs(context.Context, *GFACRequest) (*GFACResponse, error)
	GetDSErrReport(context.Context, *GDSERequest) (*GDSEResponse, error)
	GetDSSn(context.Context, *GDSSNRequest) (*GDSSNResponse, error)
	UpdateDSCommit(context.Context, *UDSCRequest) (*UDSCResponse, error)
	mustEmbedUnimplementedACServiceServer()
}

// UnimplementedACServiceServer must be embedded to have forward compatible implementations.
type UnimplementedACServiceServer struct {
}

func (UnimplementedACServiceServer) RegisterAC(context.Context, *RegistACRequest) (*RegistACResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAC not implemented")
}
func (UnimplementedACServiceServer) SelectSNs(context.Context, *StorageRequest) (*StorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectSNs not implemented")
}
func (UnimplementedACServiceServer) PutFileCommit(context.Context, *PFCRequest) (*PFCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutFileCommit not implemented")
}
func (UnimplementedACServiceServer) GetFileSNs(context.Context, *GFACRequest) (*GFACResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileSNs not implemented")
}
func (UnimplementedACServiceServer) GetDSErrReport(context.Context, *GDSERequest) (*GDSEResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDSErrReport not implemented")
}
func (UnimplementedACServiceServer) GetDSSn(context.Context, *GDSSNRequest) (*GDSSNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDSSn not implemented")
}
func (UnimplementedACServiceServer) UpdateDSCommit(context.Context, *UDSCRequest) (*UDSCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDSCommit not implemented")
}
func (UnimplementedACServiceServer) mustEmbedUnimplementedACServiceServer() {}

// UnsafeACServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ACServiceServer will
// result in compilation errors.
type UnsafeACServiceServer interface {
	mustEmbedUnimplementedACServiceServer()
}

func RegisterACServiceServer(s grpc.ServiceRegistrar, srv ACServiceServer) {
	s.RegisterService(&ACService_ServiceDesc, srv)
}

func _ACService_RegisterAC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistACRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).RegisterAC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_RegisterAC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).RegisterAC(ctx, req.(*RegistACRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACService_SelectSNs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).SelectSNs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_SelectSNs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).SelectSNs(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACService_PutFileCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PFCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).PutFileCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_PutFileCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).PutFileCommit(ctx, req.(*PFCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACService_GetFileSNs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GFACRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).GetFileSNs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_GetFileSNs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).GetFileSNs(ctx, req.(*GFACRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACService_GetDSErrReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GDSERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).GetDSErrReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_GetDSErrReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).GetDSErrReport(ctx, req.(*GDSERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACService_GetDSSn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GDSSNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).GetDSSn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_GetDSSn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).GetDSSn(ctx, req.(*GDSSNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACService_UpdateDSCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UDSCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACServiceServer).UpdateDSCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACService_UpdateDSCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACServiceServer).UpdateDSCommit(ctx, req.(*UDSCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ACService_ServiceDesc is the grpc.ServiceDesc for ACService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ACService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ACService",
	HandlerType: (*ACServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAC",
			Handler:    _ACService_RegisterAC_Handler,
		},
		{
			MethodName: "SelectSNs",
			Handler:    _ACService_SelectSNs_Handler,
		},
		{
			MethodName: "PutFileCommit",
			Handler:    _ACService_PutFileCommit_Handler,
		},
		{
			MethodName: "GetFileSNs",
			Handler:    _ACService_GetFileSNs_Handler,
		},
		{
			MethodName: "GetDSErrReport",
			Handler:    _ACService_GetDSErrReport_Handler,
		},
		{
			MethodName: "GetDSSn",
			Handler:    _ACService_GetDSSn_Handler,
		},
		{
			MethodName: "UpdateDSCommit",
			Handler:    _ACService_UpdateDSCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client_ac.proto",
}
