// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: sia_client_sn.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端发起的向存储节点放置数据分片的请求
type SiaPutFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`           //客户端ID
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`           //待存储的文件名
	Dsno          string                 `protobuf:"bytes,3,opt,name=dsno,proto3" json:"dsno,omitempty"`                   //文件分片的序号，数据分片为d-0,d-1,...，校验分片为p-0,p-1,...
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`            //文件版本号
	DataShard     []int32                `protobuf:"varint,5,rep,packed,name=dataShard,proto3" json:"dataShard,omitempty"` //序列化后的数据分片
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaPutFRequest) Reset() {
	*x = SiaPutFRequest{}
	mi := &file_sia_client_sn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaPutFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaPutFRequest) ProtoMessage() {}

func (x *SiaPutFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaPutFRequest.ProtoReflect.Descriptor instead.
func (*SiaPutFRequest) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{0}
}

func (x *SiaPutFRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SiaPutFRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SiaPutFRequest) GetDsno() string {
	if x != nil {
		return x.Dsno
	}
	return ""
}

func (x *SiaPutFRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SiaPutFRequest) GetDataShard() []int32 {
	if x != nil {
		return x.DataShard
	}
	return nil
}

// 存储节点对请求的回复
type SiaPutFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` //待存储的文件名
	Dsno          string                 `protobuf:"bytes,2,opt,name=dsno,proto3" json:"dsno,omitempty"`         //文件分片的序号，数据分片为d-0,d-1,...，校验分片为p-0,p-1,...
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`   //是否已通过验证并存储等信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaPutFResponse) Reset() {
	*x = SiaPutFResponse{}
	mi := &file_sia_client_sn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaPutFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaPutFResponse) ProtoMessage() {}

func (x *SiaPutFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaPutFResponse.ProtoReflect.Descriptor instead.
func (*SiaPutFResponse) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{1}
}

func (x *SiaPutFResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SiaPutFResponse) GetDsno() string {
	if x != nil {
		return x.Dsno
	}
	return ""
}

func (x *SiaPutFResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 客户端发起的向存储节点获取数据分片的请求
type SiaGetFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"` //客户端ID
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` //待存储的文件名
	Dsno          string                 `protobuf:"bytes,3,opt,name=dsno,proto3" json:"dsno,omitempty"`         //请求的分片号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaGetFRequest) Reset() {
	*x = SiaGetFRequest{}
	mi := &file_sia_client_sn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaGetFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaGetFRequest) ProtoMessage() {}

func (x *SiaGetFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaGetFRequest.ProtoReflect.Descriptor instead.
func (*SiaGetFRequest) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{2}
}

func (x *SiaGetFRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SiaGetFRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SiaGetFRequest) GetDsno() string {
	if x != nil {
		return x.Dsno
	}
	return ""
}

// 存储节点对请求的回复
type SiaGetFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`           //文件名
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`            //文件版本号
	DataShard     []int32                `protobuf:"varint,3,rep,packed,name=dataShard,proto3" json:"dataShard,omitempty"` //序列化后的数据分片
	Merklepath    [][]byte               `protobuf:"bytes,4,rep,name=merklepath,proto3" json:"merklepath,omitempty"`       //数据分片的可验证存储路径
	Index         int32                  `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`                //数据分片所在叶子列表中的索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaGetFResponse) Reset() {
	*x = SiaGetFResponse{}
	mi := &file_sia_client_sn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaGetFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaGetFResponse) ProtoMessage() {}

func (x *SiaGetFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaGetFResponse.ProtoReflect.Descriptor instead.
func (*SiaGetFResponse) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{3}
}

func (x *SiaGetFResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SiaGetFResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SiaGetFResponse) GetDataShard() []int32 {
	if x != nil {
		return x.DataShard
	}
	return nil
}

func (x *SiaGetFResponse) GetMerklepath() [][]byte {
	if x != nil {
		return x.Merklepath
	}
	return nil
}

func (x *SiaGetFResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 客户端发起的向存储节点更新数据分片的请求
type SiaUpdDSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`           //客户端ID
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`           //待更新的文件名
	Dsno          string                 `protobuf:"bytes,3,opt,name=dsno,proto3" json:"dsno,omitempty"`                   //待更新的文件分片号
	Datashard     []int32                `protobuf:"varint,4,rep,packed,name=datashard,proto3" json:"datashard,omitempty"` //序列化后的数据分片
	Newversion    int32                  `protobuf:"varint,5,opt,name=newversion,proto3" json:"newversion,omitempty"`      //更新后的文件分片版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaUpdDSRequest) Reset() {
	*x = SiaUpdDSRequest{}
	mi := &file_sia_client_sn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaUpdDSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaUpdDSRequest) ProtoMessage() {}

func (x *SiaUpdDSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaUpdDSRequest.ProtoReflect.Descriptor instead.
func (*SiaUpdDSRequest) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{4}
}

func (x *SiaUpdDSRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SiaUpdDSRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SiaUpdDSRequest) GetDsno() string {
	if x != nil {
		return x.Dsno
	}
	return ""
}

func (x *SiaUpdDSRequest) GetDatashard() []int32 {
	if x != nil {
		return x.Datashard
	}
	return nil
}

func (x *SiaUpdDSRequest) GetNewversion() int32 {
	if x != nil {
		return x.Newversion
	}
	return 0
}

// 存储节点对请求的回复
type SiaUpdDSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` //待存储的文件名
	Dsno          string                 `protobuf:"bytes,2,opt,name=dsno,proto3" json:"dsno,omitempty"`         //文件分片号
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`   //是否已通过验证并存储等信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaUpdDSResponse) Reset() {
	*x = SiaUpdDSResponse{}
	mi := &file_sia_client_sn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaUpdDSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaUpdDSResponse) ProtoMessage() {}

func (x *SiaUpdDSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaUpdDSResponse.ProtoReflect.Descriptor instead.
func (*SiaUpdDSResponse) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{5}
}

func (x *SiaUpdDSResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SiaUpdDSResponse) GetDsno() string {
	if x != nil {
		return x.Dsno
	}
	return ""
}

func (x *SiaUpdDSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SiaGSNSCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"` //客户端ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaGSNSCRequest) Reset() {
	*x = SiaGSNSCRequest{}
	mi := &file_sia_client_sn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaGSNSCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaGSNSCRequest) ProtoMessage() {}

func (x *SiaGSNSCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaGSNSCRequest.ProtoReflect.Descriptor instead.
func (*SiaGSNSCRequest) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{6}
}

func (x *SiaGSNSCRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SiaGSNSCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	SnId          string                 `protobuf:"bytes,2,opt,name=snId,proto3" json:"snId,omitempty"`
	Storagecost   int32                  `protobuf:"varint,3,opt,name=storagecost,proto3" json:"storagecost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiaGSNSCResponse) Reset() {
	*x = SiaGSNSCResponse{}
	mi := &file_sia_client_sn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiaGSNSCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiaGSNSCResponse) ProtoMessage() {}

func (x *SiaGSNSCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sia_client_sn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiaGSNSCResponse.ProtoReflect.Descriptor instead.
func (*SiaGSNSCResponse) Descriptor() ([]byte, []int) {
	return file_sia_client_sn_proto_rawDescGZIP(), []int{7}
}

func (x *SiaGSNSCResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SiaGSNSCResponse) GetSnId() string {
	if x != nil {
		return x.SnId
	}
	return ""
}

func (x *SiaGSNSCResponse) GetStoragecost() int32 {
	if x != nil {
		return x.Storagecost
	}
	return 0
}

var File_sia_client_sn_proto protoreflect.FileDescriptor

const file_sia_client_sn_proto_rawDesc = "" +
	"\n" +
	"\x13sia_client_sn.proto\x12\x05proto\"\x94\x01\n" +
	"\x0eSiaPutFRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04dsno\x18\x03 \x01(\tR\x04dsno\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x1c\n" +
	"\tdataShard\x18\x05 \x03(\x05R\tdataShard\"[\n" +
	"\x0fSiaPutFResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04dsno\x18\x02 \x01(\tR\x04dsno\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\\\n" +
	"\x0eSiaGetFRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04dsno\x18\x03 \x01(\tR\x04dsno\"\x9b\x01\n" +
	"\x0fSiaGetFResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1c\n" +
	"\tdataShard\x18\x03 \x03(\x05R\tdataShard\x12\x1e\n" +
	"\n" +
	"merklepath\x18\x04 \x03(\fR\n" +
	"merklepath\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x05R\x05index\"\x9b\x01\n" +
	"\x0fSiaUpdDSRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04dsno\x18\x03 \x01(\tR\x04dsno\x12\x1c\n" +
	"\tdatashard\x18\x04 \x03(\x05R\tdatashard\x12\x1e\n" +
	"\n" +
	"newversion\x18\x05 \x01(\x05R\n" +
	"newversion\"\\\n" +
	"\x10SiaUpdDSResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04dsno\x18\x02 \x01(\tR\x04dsno\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"-\n" +
	"\x0fSiaGSNSCRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\"d\n" +
	"\x10SiaGSNSCResponse\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04snId\x18\x02 \x01(\tR\x04snId\x12 \n" +
	"\vstoragecost\x18\x03 \x01(\x05R\vstoragecost2\x98\x02\n" +
	"\fSiaSNService\x12=\n" +
	"\fSiaPutFileDS\x12\x15.proto.SiaPutFRequest\x1a\x16.proto.SiaPutFResponse\x12=\n" +
	"\fSiaGetFileDS\x12\x15.proto.SiaGetFRequest\x1a\x16.proto.SiaGetFResponse\x12B\n" +
	"\x0fSiaUpdateFileDS\x12\x16.proto.SiaUpdDSRequest\x1a\x17.proto.SiaUpdDSResponse\x12F\n" +
	"\x13SiaGetSNStorageCost\x12\x16.proto.SiaGSNSCRequest\x1a\x17.proto.SiaGSNSCResponseB\x04Z\x02./b\x06proto3"

var (
	file_sia_client_sn_proto_rawDescOnce sync.Once
	file_sia_client_sn_proto_rawDescData []byte
)

func file_sia_client_sn_proto_rawDescGZIP() []byte {
	file_sia_client_sn_proto_rawDescOnce.Do(func() {
		file_sia_client_sn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sia_client_sn_proto_rawDesc), len(file_sia_client_sn_proto_rawDesc)))
	})
	return file_sia_client_sn_proto_rawDescData
}

var file_sia_client_sn_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sia_client_sn_proto_goTypes = []any{
	(*SiaPutFRequest)(nil),   // 0: proto.SiaPutFRequest
	(*SiaPutFResponse)(nil),  // 1: proto.SiaPutFResponse
	(*SiaGetFRequest)(nil),   // 2: proto.SiaGetFRequest
	(*SiaGetFResponse)(nil),  // 3: proto.SiaGetFResponse
	(*SiaUpdDSRequest)(nil),  // 4: proto.SiaUpdDSRequest
	(*SiaUpdDSResponse)(nil), // 5: proto.SiaUpdDSResponse
	(*SiaGSNSCRequest)(nil),  // 6: proto.SiaGSNSCRequest
	(*SiaGSNSCResponse)(nil), // 7: proto.SiaGSNSCResponse
}
var file_sia_client_sn_proto_depIdxs = []int32{
	0, // 0: proto.SiaSNService.SiaPutFileDS:input_type -> proto.SiaPutFRequest
	2, // 1: proto.SiaSNService.SiaGetFileDS:input_type -> proto.SiaGetFRequest
	4, // 2: proto.SiaSNService.SiaUpdateFileDS:input_type -> proto.SiaUpdDSRequest
	6, // 3: proto.SiaSNService.SiaGetSNStorageCost:input_type -> proto.SiaGSNSCRequest
	1, // 4: proto.SiaSNService.SiaPutFileDS:output_type -> proto.SiaPutFResponse
	3, // 5: proto.SiaSNService.SiaGetFileDS:output_type -> proto.SiaGetFResponse
	5, // 6: proto.SiaSNService.SiaUpdateFileDS:output_type -> proto.SiaUpdDSResponse
	7, // 7: proto.SiaSNService.SiaGetSNStorageCost:output_type -> proto.SiaGSNSCResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sia_client_sn_proto_init() }
func file_sia_client_sn_proto_init() {
	if File_sia_client_sn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sia_client_sn_proto_rawDesc), len(file_sia_client_sn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sia_client_sn_proto_goTypes,
		DependencyIndexes: file_sia_client_sn_proto_depIdxs,
		MessageInfos:      file_sia_client_sn_proto_msgTypes,
	}.Build()
	File_sia_client_sn_proto = out.File
	file_sia_client_sn_proto_goTypes = nil
	file_sia_client_sn_proto_depIdxs = nil
}
