// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sia_ac_sn.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SiaSNACServiceClient is the client API for SiaSNACService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SiaSNACServiceClient interface {
	SiaPutFileNotice(ctx context.Context, in *SiaClientStorageRequest, opts ...grpc.CallOption) (*SiaClientStorageResponse, error)
	SiaUpdateDataShardNotice(ctx context.Context, in *SiaClientUpdDSRequest, opts ...grpc.CallOption) (*SiaClientUpdDSResponse, error)
	SiaPreAuditSN(ctx context.Context, in *SiaPASNRequest, opts ...grpc.CallOption) (*SiaPASNResponse, error)
	SiaGetPosSN(ctx context.Context, in *SiaGAPSNRequest, opts ...grpc.CallOption) (*SiaGAPSNResponse, error)
}

type siaSNACServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSiaSNACServiceClient(cc grpc.ClientConnInterface) SiaSNACServiceClient {
	return &siaSNACServiceClient{cc}
}

func (c *siaSNACServiceClient) SiaPutFileNotice(ctx context.Context, in *SiaClientStorageRequest, opts ...grpc.CallOption) (*SiaClientStorageResponse, error) {
	out := new(SiaClientStorageResponse)
	err := c.cc.Invoke(ctx, "/proto.SiaSNACService/SiaPutFileNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siaSNACServiceClient) SiaUpdateDataShardNotice(ctx context.Context, in *SiaClientUpdDSRequest, opts ...grpc.CallOption) (*SiaClientUpdDSResponse, error) {
	out := new(SiaClientUpdDSResponse)
	err := c.cc.Invoke(ctx, "/proto.SiaSNACService/SiaUpdateDataShardNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siaSNACServiceClient) SiaPreAuditSN(ctx context.Context, in *SiaPASNRequest, opts ...grpc.CallOption) (*SiaPASNResponse, error) {
	out := new(SiaPASNResponse)
	err := c.cc.Invoke(ctx, "/proto.SiaSNACService/SiaPreAuditSN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siaSNACServiceClient) SiaGetPosSN(ctx context.Context, in *SiaGAPSNRequest, opts ...grpc.CallOption) (*SiaGAPSNResponse, error) {
	out := new(SiaGAPSNResponse)
	err := c.cc.Invoke(ctx, "/proto.SiaSNACService/SiaGetPosSN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiaSNACServiceServer is the server API for SiaSNACService service.
// All implementations must embed UnimplementedSiaSNACServiceServer
// for forward compatibility
type SiaSNACServiceServer interface {
	SiaPutFileNotice(context.Context, *SiaClientStorageRequest) (*SiaClientStorageResponse, error)
	SiaUpdateDataShardNotice(context.Context, *SiaClientUpdDSRequest) (*SiaClientUpdDSResponse, error)
	SiaPreAuditSN(context.Context, *SiaPASNRequest) (*SiaPASNResponse, error)
	SiaGetPosSN(context.Context, *SiaGAPSNRequest) (*SiaGAPSNResponse, error)
	mustEmbedUnimplementedSiaSNACServiceServer()
}

// UnimplementedSiaSNACServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSiaSNACServiceServer struct {
}

func (UnimplementedSiaSNACServiceServer) SiaPutFileNotice(context.Context, *SiaClientStorageRequest) (*SiaClientStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SiaPutFileNotice not implemented")
}
func (UnimplementedSiaSNACServiceServer) SiaUpdateDataShardNotice(context.Context, *SiaClientUpdDSRequest) (*SiaClientUpdDSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SiaUpdateDataShardNotice not implemented")
}
func (UnimplementedSiaSNACServiceServer) SiaPreAuditSN(context.Context, *SiaPASNRequest) (*SiaPASNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SiaPreAuditSN not implemented")
}
func (UnimplementedSiaSNACServiceServer) SiaGetPosSN(context.Context, *SiaGAPSNRequest) (*SiaGAPSNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SiaGetPosSN not implemented")
}
func (UnimplementedSiaSNACServiceServer) mustEmbedUnimplementedSiaSNACServiceServer() {}

// UnsafeSiaSNACServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SiaSNACServiceServer will
// result in compilation errors.
type UnsafeSiaSNACServiceServer interface {
	mustEmbedUnimplementedSiaSNACServiceServer()
}

func RegisterSiaSNACServiceServer(s grpc.ServiceRegistrar, srv SiaSNACServiceServer) {
	s.RegisterService(&SiaSNACService_ServiceDesc, srv)
}

func _SiaSNACService_SiaPutFileNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiaClientStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiaSNACServiceServer).SiaPutFileNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SiaSNACService/SiaPutFileNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiaSNACServiceServer).SiaPutFileNotice(ctx, req.(*SiaClientStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiaSNACService_SiaUpdateDataShardNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiaClientUpdDSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiaSNACServiceServer).SiaUpdateDataShardNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SiaSNACService/SiaUpdateDataShardNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiaSNACServiceServer).SiaUpdateDataShardNotice(ctx, req.(*SiaClientUpdDSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiaSNACService_SiaPreAuditSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiaPASNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiaSNACServiceServer).SiaPreAuditSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SiaSNACService/SiaPreAuditSN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiaSNACServiceServer).SiaPreAuditSN(ctx, req.(*SiaPASNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiaSNACService_SiaGetPosSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiaGAPSNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiaSNACServiceServer).SiaGetPosSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SiaSNACService/SiaGetPosSN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiaSNACServiceServer).SiaGetPosSN(ctx, req.(*SiaGAPSNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SiaSNACService_ServiceDesc is the grpc.ServiceDesc for SiaSNACService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SiaSNACService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SiaSNACService",
	HandlerType: (*SiaSNACServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SiaPutFileNotice",
			Handler:    _SiaSNACService_SiaPutFileNotice_Handler,
		},
		{
			MethodName: "SiaUpdateDataShardNotice",
			Handler:    _SiaSNACService_SiaUpdateDataShardNotice_Handler,
		},
		{
			MethodName: "SiaPreAuditSN",
			Handler:    _SiaSNACService_SiaPreAuditSN_Handler,
		},
		{
			MethodName: "SiaGetPosSN",
			Handler:    _SiaSNACService_SiaGetPosSN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sia_ac_sn.proto",
}
